package grupo.quatro.api_manage_escola.Respond.Exceptions;

public class AlunoNotFoundException extends UsuarioNotFoundException {
    public AlunoNotFoundException(String message) {
        super(message);
    }
}